import React from 'react';
import { useLanguage } from '../contexts/LanguageContext';

interface PrintHeaderProps {
    title?: string;
    subtitle?: string;
    month?: string;
    dateRange?: string;
    note?: string;
    themeColor?: string;
}

export const PrintHeader: React.FC<PrintHeaderProps> = ({ title, subtitle, month, dateRange, note, themeColor = 'slate' }) => {
    const { dir } = useLanguage();
    
    const colors: Record<string, string> = {
        slate: 'bg-slate-900 border-slate-900',
        teal: 'bg-teal-900 border-teal-900',
        purple: 'bg-purple-900 border-purple-900',
        indigo: 'bg-indigo-900 border-indigo-900',
        rose: 'bg-rose-900 border-rose-900',
        violet: 'bg-violet-900 border-violet-900',
    };
    
    const bgColor = colors[themeColor] || colors.slate;

    return (
        <>
            {/* Print Watermark */}
            <img 
                src="/logo.png" 
                className="fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 opacity-[0.12] w-[70%] z-[-1] pointer-events-none hidden print:block rotate-[-45deg]" 
                alt="Watermark" 
            />
            
            <div className="hidden print:flex flex-col mb-4 font-sans text-black" dir={dir}>
            {/* Header Row */}
            <div className="flex justify-between items-end border-b-4 border-black pb-2 mb-2">
                <div className="flex items-center gap-4">
                    {/* Logo Placeholder */}
                    <div className={`w-16 h-16 ${bgColor} text-white rounded-full flex items-center justify-center font-black text-2xl print-color-adjust-exact`}>
                        AJ
                    </div>
                    <div>
                        <h1 className="text-xl font-black uppercase tracking-tight leading-none">Al-Jedaani Group of Hospitals</h1>
                        <h2 className="text-sm font-bold text-gray-600 uppercase tracking-widest">Ibn Sina Hospital - Radiology Dept</h2>
                    </div>
                </div>
                
                <div className="text-right">
                    <h1 className="text-2xl font-black uppercase tracking-tighter">{title || 'Schedule Report'}</h1>
                    <p className="text-sm font-bold text-gray-500 uppercase">{subtitle || 'Monthly Roster'}</p>
                    {month && <p className="text-xs font-mono font-bold mt-1 bg-gray-200 px-2 py-0.5 rounded inline-block">{month}</p>}
                    {dateRange && <p className="text-[10px] font-bold mt-0.5 text-gray-400 uppercase">{dateRange}</p>}
                </div>
            </div>
            
            {/* Optional Note Banner */}
            {note && (
                <div className="bg-gray-100 border-l-4 border-black p-2 mb-2 text-xs font-bold italic print-color-adjust-exact">
                    NOTE: {note}
                </div>
            )}
        </div>
        </>
    );
};

export const PrintFooter: React.FC<{ themeColor?: string }> = ({ themeColor = 'slate' }) => {
    return (
        <div className="hidden print:flex flex-col mt-4 pt-2 border-t-2 border-gray-300 text-[10px] font-bold text-gray-500 uppercase justify-between">
            <div className="flex justify-between items-end">
                <div>
                    <p>Generated by Smart Employee System</p>
                    <p>{new Date().toLocaleString()}</p>
                </div>
                <div className="text-center">
                    <p className="mb-8">_________________________</p>
                    <p>Head of Department</p>
                </div>
                <div className="text-center">
                    <p className="mb-8">_________________________</p>
                    <p>Medical Director</p>
                </div>
            </div>
        </div>
    );
};
